all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
all_joints_names:
- feature0
- feature1
- feature2
- feature3
- feature4
- feature5
- feature6
- feature7
- feature8
- feature9
- feature10
- feature11
- feature12
- feature13
batch_size: 1
#bottomheight: 400
#crop: true
#cropratio: 0.4
dataset: train.mat
dataset_type: default
display_iters: 100
#global_scale: 0.8
init_weights: /home/jingpei/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
#init_weights: /home/jingpei/Desktop/test_folder/mobile_net/mobilenet_v2_1.0_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
#leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
#max_input_size: 1500
#min_input_size: 64
#minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
#net_type: mobilenet_v2_1.0
num_joints: 14
pos_dist_thresh: 17
project_path: /home/jingpei/Desktop/vrep_data
#rightwidth: 400
save_iters: 10000
#scale_jitter_lo: 0.5
#scale_jitter_up: 1.25
#topheight: 400
